"""test

Revision ID: 0cfccc3abc8c
Revises:
Create Date: 2024-08-20 12:12:43.331209

"""

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0cfccc3abc8c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("client_id", sa.Text(), nullable=True),
        sa.Column("client_secret", sa.Text(), nullable=True),
        sa.Column("access_token_url", sa.Text(), nullable=True),
        sa.Column("authorize_url", sa.Text(), nullable=True),
        sa.Column("api_base_url", sa.Text(), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("color", sa.Text(), nullable=True),
        sa.Column("icon", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("oauth_clients")
    # ### end Alembic commands ###
