"""Improve Identity Provider customization

Revision ID: 90965980bb88
Revises: aece497c3575
Create Date: 2026-03-01 11:38:40.771009

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90965980bb88'
down_revision = 'aece497c3575'
branch_labels = None
depends_on = None


def upgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_config')
    op.add_column('oauth_clients', sa.Column('display_order', sa.Integer(), nullable=True))
    op.add_column('oauth_clients', sa.Column('user_info_url', sa.String(length=255), nullable=True))
    op.add_column('oauth_clients', sa.Column('username_claim', sa.String(length=255), nullable=True))
    op.add_column('oauth_clients', sa.Column('email_claim', sa.String(length=255), nullable=True))
    op.alter_column('oauth_clients', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('oauth_clients', 'name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('oauth_clients', 'text_color',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('oauth_clients', 'background_color',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('oauth_clients', 'icon',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('oauth_clients', 'authorize_url',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('oauth_clients', 'access_token_url',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('oauth_clients', 'client_id',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('oauth_clients', 'client_secret',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('oauth_clients', 'scope',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('oauth_clients', 'api_base_url')
    # ### end Alembic commands ###


def downgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_clients', sa.Column('api_base_url', mysql.TEXT(), nullable=True))
    op.alter_column('oauth_clients', 'scope',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('oauth_clients', 'client_secret',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('oauth_clients', 'client_id',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('oauth_clients', 'access_token_url',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('oauth_clients', 'authorize_url',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('oauth_clients', 'icon',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('oauth_clients', 'background_color',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('oauth_clients', 'text_color',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('oauth_clients', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('oauth_clients', 'id',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.drop_column('oauth_clients', 'email_claim')
    op.drop_column('oauth_clients', 'username_claim')
    op.drop_column('oauth_clients', 'user_info_url')
    op.drop_column('oauth_clients', 'display_order')
    op.create_table('oauth_config',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('key', mysql.TEXT(), nullable=True),
    sa.Column('value', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
