"""Add server_metadata_url to oauth_clients

Revision ID: 99fa741f6e56
Revises: 90965980bb88
Create Date: 2026-03-07 22:20:00.000000

"""
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "99fa741f6e56"
down_revision = "90965980bb88"
branch_labels = None
depends_on = None


def upgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "oauth_clients",
        sa.Column("server_metadata_url", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oauth_clients", "server_metadata_url")
    # ### end Alembic commands ###
