"""sso configuration

Revision ID: aece497c3575
Revises: 0cfccc3abc8c
Create Date: 2024-08-20 14:08:01.066764

"""

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "aece497c3575"
down_revision = "0cfccc3abc8c"
branch_labels = None


def upgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.Text(), nullable=True),
        sa.Column("value", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("oauth_clients", sa.Column("background_color", sa.Text(), nullable=True))
    op.add_column("oauth_clients", sa.Column("text_color", sa.Text(), nullable=True))
    op.drop_column("oauth_clients", "color")
    # ### end Alembic commands ###


def downgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("oauth_clients", sa.Column("color", mysql.TEXT(), nullable=True))
    op.drop_column("oauth_clients", "text_color")
    op.drop_column("oauth_clients", "background_color")
    op.drop_table("oauth_config")
    # ### end Alembic commands ###
